/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("modular_monolith.java-library-conventions")
}

dependencies {
    implementation(project(":app:ai-adaptor"))
    implementation(project(":app:data"))
}