
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("modular_monolith.java-application-conventions")
}

dependencies {
    developmentOnly("org.springframework.boot:spring-boot-devtools")
    implementation("org.springframework.boot:spring-boot-starter-web")

    developmentOnly("org.springframework.boot:spring-boot-devtools")
    implementation("org.springframework.boot:spring-boot-starter")
    implementation(project(":app:domain"))
    implementation(project(":app:data"))
    implementation(project(":app:controller"))
}

