
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("modular_monolith.java-library-conventions")
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")

    implementation(project(":app:domain"))
}


