
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("modular_monolith.java-common-conventions")
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}
dependencies {
    testImplementation("junit:junit:4.13")
}

tasks.bootJar {enabled = true; launchScript()}
tasks.jar {enabled = false}