/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("modular_monolith.java-application-conventions")
}


dependencies {
    developmentOnly("org.springframework.boot:spring-boot-devtools")
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation("org.springframework.boot:spring-boot-starter-data-redis-reactive")
    implementation(project(":indexation:entities"))
    implementation(project(":ai"))
}

application {
    // Define the main class for the application.
    mainClass.set("modular_monolith.indexation.App")
}


